### ISSUE TITLE
Not building on WSL

### ISSUE THREAD

**Issue by LOuroboros** [Sagiri/fame-hall#1]
Hey Sagiri.
Someone wanted to have this injected into a FireRed ROM so I decided to lend them a hand because they're unable to set up a suitable environment to inject this by themself.

I got armips ready, I got the pret-preproc ready, I got all the other packages needed too I believe *(git, make, python, devkitPro's gba-dev package, cmake, and build-essential)*, and yet, when I try to build this, I get the following error:

```ruby
lunos:~/bpre-fame-hall$ make
(echo '#line 1 "src/fame-hall.c"' && pret-preproc "src/fame-hall.c" charmap.txt) | arm-none-eabi-gcc -O2 -mlong-calls -Wall -Wextra -mthumb -mno-thumb-interwork -fno-inline -fno-builtin -std=gnu11 -mabi=apcs-gnu -mcpu=arm7tdmi -march=armv4t -mtune=arm7tdmi -x c -c -MMD -I include -I gflib  -MF "build/src/fame-hall.d" -MT "build/src/fame-hall.o" -o "build/src/fame-hall.o" -
arm-none-eabi-ld --relocatable -T rom.ld  build/src/fame-hall.o -o "build/linked.o"
arm-none-eabi-size -d -B build/linked.o | awk 'FNR == 2 {print $4}' > "build/linked.sz"
python tools/freesia --rom rom.gba --start-at 0x0871A240 --needed-bytes 2840 > "build/linked.alloc"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lunos/bpre-fame-hall/tools/freesia/__main__.py", line 3, in <module>
    import sys, freesia
  File "tools/freesia/freesia.py", line 13
    def find_needed_bytes(*, rom, needed_bytes, start_at):
                           ^
SyntaxError: invalid syntax
make: *** [makefile:56: build/linked.alloc] Error 1
lunos:~/bpre-fame-hall$
```

Evidence that my terminal is reading armips and Pret's preproc just fine:
```
lunos:~/bpre-fame-hall$ armips
armips assembler v0.11.0 (Jan  8 2022 19:34:23) by Kingcom
Usage: armips [optional parameters] <FILE>

Optional parameters:
 -temp <TEMP>              Output temporary assembly data to <TEMP> file
 -sym  <SYM>               Output symbol data in the sym format to <SYM> file
 -sym2 <SYM2>              Output symbol data in the sym2 format to <SYM2> file
 -root <ROOT>              Use <ROOT> as working directory during execution
 -equ  <NAME> <VAL>        Equivalent to '<NAME> equ <VAL>' in code
 -strequ <NAME> <VAL>      Equivalent to '<NAME> equ "<VAL>"' in code
 -definelabel <NAME> <VAL> Equivalent to '.definelabel <NAME>, <VAL>' in code
 -erroronwarning           Treat all warnings like errors
 -stat                     Show area usage statistics

File arguments:
 <FILE>                    Main assembly code file
lunos:~/bpre-fame-hall$ pret-preproc
Usage: pret-preproc SRC_FILE CHARMAP_FILE [-i]
where -i denotes if input is from stdin
lunos:~/bpre-fame-hall$
```

**EDIT**: I use WSL2 with Ubuntu 20.04, for whatever that's worth.
If there's any other specific information that I need to provide, let me know.

**Comment by Zeturic** [comment]
Try doing `make PYTHON=python3`.

I personally use Arch and ArchWSL where `python` is automatically `python3`, so that's what I'm used to and what my makefiles are geared towards. I kind of forgot that most distros will have `python` be `python2`.

I should probably change that in my makefile(s).

**Comment by LOuroboros** [comment]
I completely forgot about trying this yesterday. It worked perfectly, thank you!
![wsl_3237](https://user-images.githubusercontent.com/4485172/148702424-28fbdd9e-613b-4910-97fc-3949c95fc8e4.png)
